package org.apache.jsp.WEB_002dINF.view.msg.myQalty;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myQalty_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("  \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/cmn/common.jsp", out, true);
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>전문 테스트로(TESTRO)</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"jqgrid/css/ui-lightness/jquery-ui-1.7.3.custom.css\" media=\"screen\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"jqgrid/js/src/css/ui.jqgrid.css\" media=\"screen\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"jqgrid/themes/ui.datepicker.css\" media=\"screen\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/TESTRO.ico\" type=\"image/ico\" />\r\n");
      out.write("<style>\r\n");
      out.write("html, body {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    font-size: 75%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cmn/utils/json2.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jqgrid/js/jquery-1.5.2.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cmn/jquery.blockUI.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jqgrid/js/src/i18n/grid.locale-en.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jqgrid/js/jquery.jqGrid.src.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jqgrid/js/ui.datepicker.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cmn/popupcalendar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cmn/util.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar lastsel2;\r\n");
      out.write("\tvar lastsel3; \r\n");
      out.write("\tvar maxWidth= 1100; //전체사이즈\r\n");
      out.write("\tvar maxHeight= $(window).height()-330; //전체사이즈\r\n");
      out.write("\tvar leftTemp = 230; //left메뉴사이즈\r\n");
      out.write("\t//JQ그리드 그리기\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tvar connSevrDst = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.connsevrdstcd}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\t$(\"#connSevrDstcd\").val(connSevrDst);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar userLevel = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.usrlevel}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\tif(userLevel == 03){\r\n");
      out.write("\t\t\t$(\"#projDepartment\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tjQuery(\"#list1\").jqGrid( {\r\n");
      out.write("\t\t\tmtype:'POST',    // 한글 인코딩 깨지는 문제 방지하기 위해 POST로 쓴다\r\n");
      out.write("\t\t\turl: 'msg.GetMyQaltyAction.myQalty.do',\r\n");
      out.write("\t\t\tdatatype : \"json\",\r\n");
      out.write("\t\t\tcolNames : [ '프로젝트번호', '프로젝트명', '테스트단계', '테스트시작일자', '테스트종료일자' ],\r\n");
      out.write("\t\t\tcolModel : [ \r\n");
      out.write("\t\t\t\t{name : 'projNo',index : 'PROJNO',width : 170,align : \"left\"},\r\n");
      out.write("\t\t\t\t{name : 'projName',index : 'PROJNAME',width : 323,editable : true,align : \"left\"}, \r\n");
      out.write("\t\t\t\t{name : 'testStgeName',\tindex : 'TESTSTGENAME',\twidth : 170,align : \"left\"}, \r\n");
      out.write("\t\t\t\t{name : 'testStartYMS',\tindex : 'TESTSTARTYMS',\twidth : 170,align : \"center\", formatter:gridDateFmatter, formatoptions: {srcformat:'yMd', newformat:'y-M-d'}, unformat:gridDateUnFmatter}, \r\n");
      out.write("\t\t\t\t{name : 'testEndYMS',index : 'TESTENDYMS',width : 170,\talign : \"center\", formatter:gridDateFmatter, formatoptions: {srcformat:'yMd', newformat:'y-M-d'}, unformat:gridDateUnFmatter}\r\n");
      out.write("\t\t\t],\t\r\n");
      out.write("\t\t\theight: maxHeight,\r\n");
      out.write("\t\t\trownumbers: true,//리스트 seq 사용 여부 \r\n");
      out.write("\t\t\tgridview: true,\r\n");
      out.write("\t\t\trowNum:30, //페이지 row 갯수 \r\n");
      out.write("\t\t    rowList:[20,30,50], //페이지 row 갯수 변경 option( bottom selectbox) \r\n");
      out.write("\t\t\tsortname : 'PROJNO',\r\n");
      out.write("\t\t\tviewrecords : true,\r\n");
      out.write("\t\t\tsortorder : \"asc\",\r\n");
      out.write("\t\t\tautowidth: true,\r\n");
      out.write("\t\t\tpager: '#pager', //bottom paging 지정 \r\n");
      out.write("\t\t\tloadComplete: function(xhr){\r\n");
      out.write("\t\t\t\tif (xhr.errCd) alert('에러코드 : ' + xhr.errCd + \"\\n에러메시지 : \" + xhr.errMsg);\r\n");
      out.write("\t\t\t\t $(\"#list1\").setGridHeight(maxHeight+1, true);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t setSelection('list1');\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tjsonReader : {\r\n");
      out.write("\t\t\t\troot : \"rows\",\r\n");
      out.write("\t\t\t\tpage : \"page\",\r\n");
      out.write("\t\t\t\ttotal : \"total\",\r\n");
      out.write("\t\t\t\trecords : \"records\",\r\n");
      out.write("\t\t\t\trepeatitems : false,\r\n");
      out.write("\t\t\t\tcell : \"cell\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonRightClickRow: function (rowid, iRow, iCol, e) {//우클릭 브라우져메뉴 block\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//윈도우사이즈와 맞춰 조절됨\r\n");
      out.write("\t\t$(window).bind('resize', function() {\r\n");
      out.write("\t\t\tvar windowWindth = $(window).width()-leftTemp;\r\n");
      out.write("\t\t\tif (windowWindth > maxWidth) {\r\n");
      out.write("\t\t\t\t$(\"#list1\").setGridWidth(windowWindth, true);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tjQuery(\"#list1\").jqGrid('gridResize',{minWidth:maxWidth ,maxWidth:'100%'});\r\n");
      out.write("\t\t\t\t$(\"#list1\").setGridWidth(windowWindth, false);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//-------- 그리드 hight ------------------------------\r\n");
      out.write("\t\t\twindowHeight = $(window).height() - 350;           // 마이너스값 수정. \r\n");
      out.write("\t\t\t$(\"#list1\").setGridHeight(windowHeight, true);         \r\n");
      out.write("\t\t    //---------------------------------------------------\t\r\n");
      out.write("\t\t}).trigger('resize');\r\n");
      out.write("\t\t//입력필드에 전체 값 넣어주고 포커스 할경우사라지게 하기\r\n");
      out.write("\t\tsetAllSearch('qaltyMgtProjName1');\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"input,select\").keydown(function(e){\r\n");
      out.write("\t\t   \tif(e.keyCode == 13){\r\n");
      out.write("\t\t   \t\tdoSearch();\r\n");
      out.write("\t\t   \t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction bodyreload(){\r\n");
      out.write("\t\tvar hidenYn = $(\"body\").attr(\"hideYn\");\r\n");
      out.write("\t\tif(\"Y\" == hidenYn){ //left 메뉴 hidden\r\n");
      out.write("\t\t\tleftTemp=40;\r\n");
      out.write("\t\t}else{ //left 메뉴 show\r\n");
      out.write("\t\t\tleftTemp=230;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(window).trigger('resize');\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//<!--\r\n");
      out.write("\tfunction MM_swapImgRestore() { //v3.0\r\n");
      out.write("\t\tvar i, x, a = document.MM_sr;\r\n");
      out.write("\t\tfor (i = 0; a && i < a.length && (x = a[i]) && x.oSrc; i++)\r\n");
      out.write("\t\t\tx.src = x.oSrc;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction MM_preloadImages() { //v3.0\r\n");
      out.write("\t\tvar d = document;\r\n");
      out.write("\t\tif (d.image) {\r\n");
      out.write("\t\t\tif (!d.MM_p)\r\n");
      out.write("\t\t\t\td.MM_p = new Array();\r\n");
      out.write("\t\t\tvar i, j = d.MM_p.length, a = MM_preloadimage.arguments;\r\n");
      out.write("\t\t\tfor (i = 0; i < a.length; i++)\r\n");
      out.write("\t\t\t\tif (a[i].indexOf(\"#\") != 0) {\r\n");
      out.write("\t\t\t\t\td.MM_p[j] = new Image;\r\n");
      out.write("\t\t\t\t\td.MM_p[j++].src = a[i];\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction MM_findObj(n, d) { //v4.01\r\n");
      out.write("\t\tvar p, i, x;\r\n");
      out.write("\t\tif (!d)\r\n");
      out.write("\t\t\td = document;\r\n");
      out.write("\t\tif ((p = n.indexOf(\"?\")) > 0 && parent.frames.length) {\r\n");
      out.write("\t\t\td = parent.frames[n.substring(p + 1)].document;\r\n");
      out.write("\t\t\tn = n.substring(0, p);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!(x = d[n]) && d.all)\r\n");
      out.write("\t\t\tx = d.all[n];\r\n");
      out.write("\t\tfor (i = 0; !x && i < d.forms.length; i++)\r\n");
      out.write("\t\t\tx = d.forms[i][n];\r\n");
      out.write("\t\tfor (i = 0; !x && d.layers && i < d.layers.length; i++)\r\n");
      out.write("\t\t\tx = MM_findObj(n, d.layers[i].document);\r\n");
      out.write("\t\tif (!x && d.getElementById)\r\n");
      out.write("\t\t\tx = d.getElementById(n);\r\n");
      out.write("\t\treturn x;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction MM_swapImage() { //v3.0\r\n");
      out.write("\t\tvar i, j = 0, x, a = MM_swapImage.arguments;\r\n");
      out.write("\t\tdocument.MM_sr = new Array;\r\n");
      out.write("\t\tfor (i = 0; i < (a.length - 2); i += 3)\r\n");
      out.write("\t\t\tif ((x = MM_findObj(a[i])) != null) {\r\n");
      out.write("\t\t\t\tdocument.MM_sr[j++] = x;\r\n");
      out.write("\t\t\t\tif (!x.oSrc)\r\n");
      out.write("\t\t\t\t\tx.oSrc = x.src;\r\n");
      out.write("\t\t\t\tx.src = a[i + 2];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction MM_openBrWindow(theURL, winName, features) { //v2.0\r\n");
      out.write("\t\twindow.open(theURL, winName, features);\r\n");
      out.write("\t}\r\n");
      out.write("\t//-->\r\n");
      out.write("\r\n");
      out.write("\t// iframe resize\r\n");
      out.write("\tfunction autoResize(i) {\r\n");
      out.write("\t\tvar iframeHeight = (i).contentWindow.document.body.scrollHeight;\r\n");
      out.write("\t\t(i).height = iframeHeight + 20;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//나의 프로젝트 단계정보 조회 \r\n");
      out.write("\tfunction doSearch() {\t\r\n");
      out.write("\t\tvar par = \"\";\r\n");
      out.write("\t\tvar projName = getAllSearchValue('qaltyMgtProjName1');\r\n");
      out.write("\t\tpar = \"?projName=\" + encodeURIComponent(projName);\r\n");
      out.write("\t\t$('#list1').setGridParam({\r\n");
      out.write("\t\t\tpage: 1,\r\n");
      out.write("\t\t\turl:'msg.GetMyQaltyAction.myQalty.do',\r\n");
      out.write("\t\t\tpostData: {\r\n");
      out.write("\t\t\t\tprojName: projName\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#list1').trigger(\"reloadGrid\");\t\r\n");
      out.write("\t\t$(\"#search_button1\").focus();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//프로젝트 정보 설정 저장\r\n");
      out.write("\tfunction doSave() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar fromArray;\r\n");
      out.write("\t\tfromArray = jQuery(\"#list1\").jqGrid('getGridParam','selarrrow');\r\n");
      out.write("\t\tvar select = jQuery(\"#list1\").getGridParam(\"selrow\");\r\n");
      out.write("\t\tvar rows= jQuery(\"#list1\").jqGrid('getRowData',select);\r\n");
      out.write("\t\tvar usrid = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.usrid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';    //사용자id\r\n");
      out.write("\t\tvar connSevrDstcd = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.connsevrdstcd}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';    //접속서버\r\n");
      out.write("\t\tvar postData = JSON.stringify(rows);\r\n");
      out.write("\t\tif(select == null){\r\n");
      out.write("\t\t\talert(\"설정하고자 하는 프로젝트정보가 없습니다.\");\t\r\n");
      out.write("\t\t}else{\t\r\n");
      out.write("\t\t\tif(confirm(\"프로젝트 정보를 설정하시겠습니까?\")){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t        type:\"POST\",\r\n");
      out.write("\t\t\t\t\tdata:{\"jgGridData\":postData,\r\n");
      out.write("\t\t\t\t\t\t\"usrId\":usrid,\r\n");
      out.write("\t\t\t\t\t\t\"connSevrDstcd\":connSevrDstcd },\r\n");
      out.write("\t\t\t        dataType:\"json\",\r\n");
      out.write("\t\t\t        async : true,\r\n");
      out.write("\t\t\t        url:\"msg.RegisterMyQaltyAction.myQalty.do\",\r\n");
      out.write("\t\t\t        success:function(data, status) {\r\n");
      out.write("\t\t\t        \tif (data.errCd){\r\n");
      out.write("\t\t\t\t        \talert('에러코드 : ' + data.errCd + \"\\n에러메시지 : \" + data.errMsg);\r\n");
      out.write("\t\t\t        \t}else{\r\n");
      out.write("\t\t\t\t\t        alert(\"테스트 진행 프로젝트를 다음과 같이 설정하셨습니다.\\r\\n\\r\\n프로젝트명 : \"+rows.projName+\"\\r\\n테스트단계 : \"+rows.testStgeName);\r\n");
      out.write("\t\t\t\t        \treload();\r\n");
      out.write("\t\t\t        \t}\r\n");
      out.write("\t\t\t        },\r\n");
      out.write("\t\t\t        error:function(request, status, error) {\r\n");
      out.write("\t\t\t        \talert(\"프로젝트 설정중에 오류가 발생하였습니다.[\" + error + \"]\"); \r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    });\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//화면 재 출력\r\n");
      out.write("\tfunction reload(){\r\n");
      out.write("\t\tlocation.href=\"msg.myQalty.myQalty.do\";\r\n");
      out.write("\t}\r\n");
      out.write("\t//프로젝트 명 검색어 초기화\r\n");
      out.write("\tfunction doMgtClaer() {\r\n");
      out.write("\t\t$(\"#qaltyMgtProjName2\").val(\"\");\r\n");
      out.write("\t}\r\n");
      out.write("\t//테스트 환경설정 저장\r\n");
      out.write("\tfunction doEnviSave() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar frm = document.frm3;\r\n");
      out.write("\t\tvar useEmpid ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.usrid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\t\t\t\t\t\t//세션 ID\r\n");
      out.write("\t\tvar connSevrDstcdName = $(\"#connSevrDstcd > :selected\").html();;\t//선택한값의 html 값\r\n");
      out.write("\t\t//접속서버 없으면 저장 불가\r\n");
      out.write("\t\tif (frm.connSevrDstcd.value == \"\") {\r\n");
      out.write("\t\t\talert(\"접속 서버를 지정하세요.\");\r\n");
      out.write("\t\t\tfrm.connSevrDstcd.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t        type:\"POST\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\"connSevrDstcdnm\":connSevrDstcdName,\r\n");
      out.write("\t\t\t\t\"connSevrDstcd\":frm.connSevrDstcd.value,\r\n");
      out.write("\t    \t\t\"usrId\":useEmpid},\r\n");
      out.write("\t        dataType:\"json\",\r\n");
      out.write("\t        async : true,\r\n");
      out.write("\t        url:\"msg.RegisterTestEnviAction.myQalty.do\",\r\n");
      out.write("\t        success:function(data, status) {\r\n");
      out.write("\t        \tif (data.errCd){\r\n");
      out.write("\t\t        \talert('에러코드 : ' + data.errCd + \"\\n에러메시지 : \" + data.errMsg);\r\n");
      out.write("\t        \t}else{\r\n");
      out.write("\t\t\t        alert(\"접속시스템이 '\" + connSevrDstcdName + \"'으로 설정되었습니다.\");\r\n");
      out.write("\t\t        \treload();\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t        },\r\n");
      out.write("\t        error:function(request, status, error) {\r\n");
      out.write("\t        \talert(\"접속시스템 설정중에 오류가 발생하였습니다.[\" + error + \"]\"); \r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertProject(winName) {\r\n");
      out.write("\t\tvar lastModfiEmpLevel = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.usrlevel}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\t//사용자 관리 수정 \r\n");
      out.write("\t\tvar theURL = \"msg.popMyQalty.popMyQalty.do\";\r\n");
      out.write("\t\tif(winName == \"수정\"){\r\n");
      out.write("\t\t\tvar select = jQuery(\"#list1\").getGridParam(\"selrow\");\r\n");
      out.write("\t\t\tvar rows= jQuery(\"#list1\").jqGrid('getRowData',select);\r\n");
      out.write("\t\t\tvar projNo = rows.projNo;\r\n");
      out.write("\t\t\tvar testStgeName = rows.testStgeName;\r\n");
      out.write("\t\t\tvar postData = JSON.stringify(rows);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(select == null){\r\n");
      out.write("\t\t\t\talert(\"수정할 프로젝트를 선택해주세요\");\t\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\ttheURL = theURL+\"?newSave=N&projNo=\"+encodeURIComponent(projNo)+\"&testStgeName=\"+encodeURIComponent(testStgeName)+\"&lastModfiEmpLevel=\"+ lastModfiEmpLevel;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\tvar retrunValue = window.showModalDialog(theURL,winName,'center:yes;dialogWidth=480px; dialogHeight=233px; scroll=no; status=no; help=no; resizable:no; ');\r\n");
      out.write("\t\t\tif(retrunValue == 1){\r\n");
      out.write("\t\t\t\tdoSearch();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t//사용자 관리 신규 등록\r\n");
      out.write("\t\t}else if(winName == \"신규\"){\r\n");
      out.write("\t\t\ttheURL = theURL+\"?newSave=Y&projNo=&&testStgeName=&lastModfiEmpLevel=\"+ encodeURIComponent(lastModfiEmpLevel);\r\n");
      out.write("\t\t\tvar retrunValue = window.showModalDialog(theURL,winName,'center:yes;dialogWidth=480px; dialogHeight=233px; scroll=no; status=no; help=no; resizable:no; ');\r\n");
      out.write("\t\t\tif(retrunValue == 1){\r\n");
      out.write("\t\t\t\tdoSearch();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//프로젝트 삭제\r\n");
      out.write("\tfunction deleteProject() {\r\n");
      out.write("\t\tvar select = jQuery(\"#list1\").getGridParam(\"selrow\");\r\n");
      out.write("\t\tvar rows= jQuery(\"#list1\").jqGrid('getRowData',select);\r\n");
      out.write("\t\tvar projNo = rows.projNo;\r\n");
      out.write("\t\tvar projName = rows.projName;\r\n");
      out.write("\t\tvar testStgeName = rows.testStgeName;\r\n");
      out.write("\t\tvar postData = JSON.stringify(rows);\r\n");
      out.write("\t\tif(select == null){\r\n");
      out.write("\t\t\talert(\"삭제할 프로젝트를 선택해주세요.\");\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(confirm(\"프로젝트명 : \"+projName+\"\\r\\n테스트단계 : \"+testStgeName+\"\\r\\n\\r\\n선택한 프로젝트/테스트단계 정보를 삭제 하시겠습니까?\")){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t        type:\"POST\",\r\n");
      out.write("\t\t\t\t\tdata:{\"projNo\":projNo,\r\n");
      out.write("\t\t\t\t\t\t\"testStgeName\":testStgeName},\r\n");
      out.write("\t\t\t        dataType:\"json\",\r\n");
      out.write("\t\t\t        async : true,\r\n");
      out.write("\t\t\t        url:\"msg.getProjectDelete.MyQalty.do\",\r\n");
      out.write("\t\t\t        success:function(data, status) {\r\n");
      out.write("\t\t\t        \tif (data.errCd){\r\n");
      out.write("\t\t\t\t        \talert('에러코드 : ' + data.errCd + \"\\n에러메시지 : \" + data.errMsg);\r\n");
      out.write("\t\t\t        \t}else{\r\n");
      out.write("\t\t\t\t\t        if(data.ProjCheck == 0){\r\n");
      out.write("\t\t\t\t\t\t        alert(\"현재 사용중인 프로젝트 정보는 삭제하실 수 없습니다.\\r\\n테스트케이스 및 테스트결과서가 존재합니다.\");\r\n");
      out.write("\t\t\t\t\t        }else{\r\n");
      out.write("\t\t\t\t        \t\talert(\"선택한 프로제트가 삭제 되었습니다.\");\r\n");
      out.write("\t\t\t\t        \t\tdoSearch();\r\n");
      out.write("\t\t\t\t\t        }\r\n");
      out.write("\t\t\t        \t}\r\n");
      out.write("\t\t\t        },\r\n");
      out.write("\t\t\t        error:function(request, status, error) {\r\n");
      out.write("\t\t\t        \talert(\"프로젝트 삭제중에 오류가 발생하였습니다.[\" + error + \"]\"); \r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    });\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\t\r\n");
      out.write("\t//사용자 비밀번호 변경\r\n");
      out.write("\tfunction passChacnge(){\r\n");
      out.write("\t\tvar url = \"msg.popUserPass.popUserPass.do\";\r\n");
      out.write("\t    var returnValue = window.showModalDialog(url,window,'center:yes;dialogWidth=470px; dialogHeight=206px; scroll:no; status:no; help:no; resizable:no; location:no; ');\r\n");
      out.write("\t}\t\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#FFFFFF\" background=\"images/left_menu_bg.jpg\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\" >\r\n");
      out.write("\r\n");
      out.write("<div id=\"Minwidth\">\r\n");
      out.write("        <div id=\"Page\">\r\n");
      out.write("            <div id=\"contents\">\r\n");
      out.write("            <!-- top menu 시작 --> \r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/cmn/topMenu.jsp", out, true);
      out.write("\r\n");
      out.write("            <!-- top menu 끝 -->   \r\n");
      out.write("            \r\n");
      out.write("                <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"Table_01\">\r\n");
      out.write("                    <tr> \r\n");
      out.write("\t\t\t\t\t\t<!-- left menu 시작 -->\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/cmn/leftMenu.jsp", out, true);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- left menu 끝 -->\r\n");
      out.write("                        <td valign=\"top\">\r\n");
      out.write("                            <table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"15\" cellspacing=\"0\">\r\n");
      out.write("                                <tr> \r\n");
      out.write("                                  <td valign=\"top\">\r\n");
      out.write("                                  <table border=0 cellpadding=0 cellspacing=0 width=100%>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                      <td width=\"20\"><img src=\"images/title_bullet1.gif\"></td>\r\n");
      out.write("                                      <td width=\"165\" class=\"sub_tit\">나의 프로젝트 정보설정</td>\r\n");
      out.write("                                      <td valign=\"bottom\" class=\"point_text\" id=\"flowMsg\" >프로젝트를 추가 하거나 수정 할 수 있습니다.</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr >\r\n");
      out.write("                                      <td background=\"images/tit_line_bg.gif\" height=\"6\" colspan=\"3\"><img src=\"images/tit_line_bg.gif\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr >\r\n");
      out.write("                                      <td height=\"10\" colspan=\"3\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                  </table>\r\n");
      out.write("                                 <form name=\"frm1\" method=\"post\">\r\n");
      out.write("                                 <input name=\"projNo\" type=\"hidden\" />\r\n");
      out.write("                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td class=\"sub_tit02\">나의 프로젝트 단계정보</td>\r\n");
      out.write("                                        <td align=\"right\">\r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                        <img src=\"images/bullet_round_blue.gif\" width=\"8\" height=\"10\" hspace=\"4\"><span class=\"board_title\">프로젝트명 :</span>\r\n");
      out.write("                                        <span class=\"input_result\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.projname}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                        <img src=\"images/bullet_round_blue.gif\" width=\"8\" height=\"10\" hspace=\"4\"><span class=\"board_title\">테스트단계 :</span>\r\n");
      out.write("                                        <span class=\"input_result\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.teststgename}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("</span></td>\r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                    <table width=\"100%\" border=\"0\" cellpadding=\"5\" cellspacing=\"1\" bgcolor=\"#baccdc\">\r\n");
      out.write("                                          <tr>\r\n");
      out.write("                                            <td bgcolor=\"#e1e9f0\">\r\n");
      out.write("                                              <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"5\">\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                      <td bgcolor=\"#FFFFFF\">\r\n");
      out.write("                                                          <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n");
      out.write("                                                              <tr>\r\n");
      out.write("                                                                <td width=\"80\" class=\"box_txt\">프로젝트 명:</td>\r\n");
      out.write("                                                                <td width=\"344\">\r\n");
      out.write("                                                                \t<input name=\"qaltyMgtProjName1\" id=\"qaltyMgtProjName1\" type=\"text\" class=\"input_topinq\" style=\"width:300px\" maxlength=\"100\">\r\n");
      out.write("                                                                \t<img src=\"images/btn_eraser.gif\" alt=\"삭제\" width=\"23\" height=\"21\" hspace=\"4\" align=\"absmiddle\" onClick=\"{$('#qaltyMgtProjName1').val('').focus()}\" style=\"cursor: pointer\">\r\n");
      out.write("                                                                </td>\r\n");
      out.write("                                                                <td>\r\n");
      out.write("\t                                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"right\">\r\n");
      out.write("\t                                                                  <tr>\r\n");
      out.write("\t                                                                    <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("\t                                                                    <td background=\"images/btn_img_02.gif\" class=\"btn_text\" id=\"search_button1\" style=\"cursor:pointer\" onclick=\"doSearch(); return false;\">조 회</td>\r\n");
      out.write("\t                                                                    <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("\t                                                                  </tr>\r\n");
      out.write("\t                                                                </table>\r\n");
      out.write("                                                                </td>\r\n");
      out.write("                                                              </tr>\r\n");
      out.write("                                                          </table>\r\n");
      out.write("                                                      </td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                              </table>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                          </tr>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td height=\"10\" colspan=\"3\"></td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td class=\"sub_tit02\">프로젝트 목록</td>\r\n");
      out.write("\t\t\t\t\t                  <td id=\"projDepartment\">\r\n");
      out.write("\t\t\t\t\t\t                  <table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t                    <tr>\r\n");
      out.write("\t\t\t\t\t\t                      <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t                      <td background=\"images/btn_img_02.gif\" class=\"btn_text\" style=\"cursor:pointer\" onclick=\"deleteProject(); return false;\">삭제</td>\r\n");
      out.write("\t\t\t\t\t\t                      <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t                    </tr>\r\n");
      out.write("\t\t\t\t\t\t                  </table>\r\n");
      out.write("\t\t\t\t\t\t                  <table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t                    <tr>\r\n");
      out.write("\t\t\t\t\t\t                      <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t                      <td background=\"images/btn_img_02.gif\" class=\"btn_text\" style=\"cursor:pointer\" onclick=\"insertProject('수정'); return false;\">수정</td>\r\n");
      out.write("\t\t\t\t\t\t                      <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t                    </tr>\r\n");
      out.write("\t\t\t\t\t\t                  </table>\r\n");
      out.write("\t\t\t\t\t\t                    <table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t                    <tr>\r\n");
      out.write("\t\t\t\t\t\t                      <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t                      <td background=\"images/btn_img_02.gif\" class=\"btn_text\" style=\"cursor:pointer\" onclick=\"insertProject('신규'); return false;\">프로젝트 추가 </td>\r\n");
      out.write("\t\t\t\t\t\t                      <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t                    </tr>\r\n");
      out.write("\t\t\t\t\t\t                  </table>\t\t                    \r\n");
      out.write("\t\t\t\t\t                    </td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                    <table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"2\" cellspacing=\"1\" bgcolor=\"#baccdc\">\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td valign=\"top\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("                                        <table id=\"list1\"></table>\r\n");
      out.write("                                        <div id=\"pager\"></div> \r\n");
      out.write("                                        </td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td height=\"5\"></td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td height=\"10\"><table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                          <tr>\r\n");
      out.write("                                            <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                            <td background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick =\"doSave(); return false;\" style=\"cursor:pointer\" title=\"선택한 프로젝트로 프로젝트정보를 설정합니다.\">프로젝트 정보설정</td>\r\n");
      out.write("                                            <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                          </tr>\r\n");
      out.write("                                                                                </table></td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                            </form>\r\n");
      out.write("<!--                        <form name=\"frm3\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"strCd\" name=\"strCd\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"strNm\" name=\"strNm\" />\r\n");
      out.write("                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td class=\"sub_tit02\">테스트 환경 설정</td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                    <table width=\"100%\" border=\"0\" cellpadding=\"5\" cellspacing=\"1\" bgcolor=\"#baccdc\">\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td bgcolor=\"#e1e9f0\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"5\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                              <td bgcolor=\"#FFFFFF\">\r\n");
      out.write("                                                <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                        <td width=\"80\" class=\"box_txt\">접속시스템 :</td>\r\n");
      out.write("                                                        <td>\r\n");
      out.write("                                                          <select name=\"connSevrDstcd\"  id=\"connSevrDstcd\" class=\"menu\" style=\"width:140px\">\r\n");
      out.write("                                                          \t<option value=\"\" >== 선 택 ==</option>\r\n");
      out.write("                                                          \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                                          </select>\r\n");
      out.write("                                                      </td>                        \r\n");
      out.write("                                                   </tr>     \r\n");
      out.write("                                                </table>\r\n");
      out.write("                                              </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </table></td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td height=\"5\"></td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td height=\"10\">\r\n");
      out.write("                                        <table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                              <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                              <td background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick=\"doEnviSave(); return false;\" title=\"입력된 정보로 테스트환경을 설정합니다.\" style=\"cursor:pointer\">테스트환경설정</td>\r\n");
      out.write("                                              <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                        <table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t                    <tr>\r\n");
      out.write("\t\t\t\t\t\t                      <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t                      <td background=\"images/btn_img_02.gif\" class=\"btn_text\" style=\"cursor:pointer\" onclick=\"passChacnge(); return false;\">비밀번호 변경</td>\r\n");
      out.write("\t\t\t\t\t\t                      <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t                    </tr>\r\n");
      out.write("\t\t\t\t\t\t                  </table>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                    </table> \r\n");
      out.write("                           \t\t\t</form> -->   \r\n");
      out.write("                            \r\n");
      out.write("                                   </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/view/msg/myQalty/myQalty.jsp(512,59) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("list");
    // /WEB-INF/view/msg/myQalty/myQalty.jsp(512,59) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mciArray}", java.lang.Object.class, (PageContext)_jspx_page_context, null, false));
    // /WEB-INF/view/msg/myQalty/myQalty.jsp(512,59) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("status");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t                                        <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.key}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write(' ');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.val}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("                                                            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
