package org.apache.jsp.WEB_002dINF.view.msg.tcmng;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tcmng_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" />\r\n");
      out.write("<title>전문 테스트로(TESTRO)</title>\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"jqgrid/css/ui-lightness/jquery-ui-1.7.3.custom.css\" media=\"screen\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"jqgrid/js/src/css/ui.jqgrid.css\" media=\"screen\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/TESTRO.ico\" type=\"image/ico\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("html, body {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    font-size: 75%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"jqgrid/js/jquery-1.5.2.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cmn/jquery.blockUI.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jqgrid/js/src/i18n/grid.locale-en.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jqgrid/js/jquery.jqGrid.src.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jqgrid/js/jquery.contextmenu-fixed.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cmn/utils/json2.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/msg/tcmng/tcmng.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cmn/util.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cmn/validation_v01.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cmn/popupcalendar.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!-- \r\n");
      out.write("\r\n");
      out.write("function MM_swapImgRestore() { //v3.0\r\n");
      out.write("var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;\r\n");
      out.write("}\r\n");
      out.write("function MM_preloadimage() { //v3.0\r\n");
      out.write("var d=document; if(d.image){ if(!d.MM_p) d.MM_p=new Array();\r\n");
      out.write("var i,j=d.MM_p.length,a=MM_preloadimage.arguments; for(i=0; i<a.length; i++)\r\n");
      out.write("if (a[i].indexOf(\"#\")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function MM_findObj(n, d) { //v4.01\r\n");
      out.write("var p,i,x;  if(!d) d=document; if((p=n.indexOf(\"?\"))>0&&parent.frames.length) {\r\n");
      out.write("d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}\r\n");
      out.write("if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];\r\n");
      out.write("for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);\r\n");
      out.write("if(!x && d.getElementById) x=d.getElementById(n); return x;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function MM_swapImage() { //v3.0\r\n");
      out.write("var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)\r\n");
      out.write("if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}\r\n");
      out.write("}\r\n");
      out.write("function MM_openBrWindow(theURL,winName,features) { //v2.0\r\n");
      out.write("window.open(theURL,winName,features);\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("\r\n");
      out.write("// iframe resize\r\n");
      out.write("function autoResize(i)\r\n");
      out.write("{\r\n");
      out.write("var iframeHeight=\r\n");
      out.write("(i).contentWindow.document.body.scrollHeight;\r\n");
      out.write("(i).height=iframeHeight+20;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#FFFFFF\" background=\"images/left_menu_bg.jpg\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\" onLoad=\"MM_preloadimage('images/top_menu_01_02.jpg','images/top_menu_02_02.jpg','images/top_menu_03_02.jpg','images/top_menu_04_02.jpg','images/top_menu_05_02.jpg','images/top_menu_06_02.jpg','images/top_menu_07_02.jpg','images/신규생성_02.jpg','images/불러오기_02.jpg','images/저장_02.jpg','images/초기화_02.jpg')\">\r\n");
      out.write("\r\n");
      out.write("<form name=\"frmname\" method=\"post\">\r\n");
      out.write("\t<!-- 세션정보 -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"usrName\" \tid=\"usrName\" value=\"테스터\"  />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 테스트케이스 정보 -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"chnlDstcd\" \tid=\"chnlDstcd\"  \tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${chnlDstcd}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"tranCd\" \t\tid=\"tranCd\" \t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tranCd}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"tranName\" \tid=\"tranName\"  \t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tranName}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"fldDiv\" \t\tid=\"fldDiv\"  />\r\n");
      out.write("\t<input type=\"hidden\" name=\"tsCaseID\" \tid=\"tsCaseID\"  \t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tsCaseID}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"tsCaseName\" \tid=\"tsCaseName\"\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tsCaseName}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"tsCaseDesc\" \tid=\"tsCaseDesc\"\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tsCaseDesc}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"acmplNth\" \tid=\"acmplNth\"\t\tvalue=\"\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 로그인 정보 -->\t\r\n");
      out.write("\t<input type=\"hidden\" name=\"usrid\" \t\t id=\"usrid\"  \t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.usrid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"usrname\" \t id=\"usrname\"\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.usrname}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"teststartyms\" id=\"teststartyms\"\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.teststartyms}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"testendyms\" \t id=\"testendyms\"\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.testendyms}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"usrlevel\" \t  id=\"usrlevel\"\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.projno}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"projno\" \t \t  id=\"projno\"\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.projno}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"projname\" \t  id=\"projname\"\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.projname}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"teststgename\"  id=\"teststgename\"\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.teststgename}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"connsevrdstcd\" id=\"connsevrdstcd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.connsevrdstcd}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 데이터자동생성 -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"gridCnt\" id=\"gridCnt\" value=\"\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"EngAutoDataHeaderKey\" id=\"EngAutoDataHeaderKey\" value=\"\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"EngAutoDataHeader\" id=\"EngAutoDataHeader\" value=\"\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"KorAutoDataHeader\" id=\"KorAutoDataHeader\" value=\"\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"autoMaxLength\" id=\"autoMaxLength\" value=\"\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"autoDataPosition\" id=\"autoDataPosition\" value=\"\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"cellEditMode\" id=\"cellEditMode\" value=\"\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"NMcheck\" id=\"NMcheck\" value=\"\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"totalarray\" id=\"totalarray\" value=\"\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 체크포인트팝업 정보 // 테스트데이터 저장후 활용 정보  -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"tsdataID\" id=\"tsdataID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tsDataID}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 반복부 정보 -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"rptMap\" id=\"rptMap\" value=\"\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 체크포인트팝업 정보 -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"chkYNVal\" id=\"chkYNVal\" value=\"\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 실행시 체크된 ID List -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"cklst\" id=\"cklst\" value=\"\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 테스트케이스 테스트데이터 최대등록건수 -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"tcDataMaxCnt\" id=\"tcDataMaxCnt\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tcDataMaxCnt}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\r\n");
      out.write("    <div id=\"Minwidth\">\r\n");
      out.write("        <div id=\"Page\">\r\n");
      out.write("            <div id=\"contents\">\r\n");
      out.write("            <!-- top menu 시작 --> \r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/cmn/topMenu.jsp", out, true);
      out.write("\r\n");
      out.write("            <!-- top menu 끝 -->   \r\n");
      out.write("            \r\n");
      out.write("                <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"Table_01\">\r\n");
      out.write("                    <tr> \r\n");
      out.write("\t\t\t\t\t\t<!-- left menu 시작 -->\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/cmn/leftMenu.jsp", out, true);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- left menu 끝 -->\r\n");
      out.write("                        <td valign=\"top\">\r\n");
      out.write("                            <table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"15\" cellspacing=\"0\">\r\n");
      out.write("                                <tr> \r\n");
      out.write("                                  <td valign=\"top\">\r\n");
      out.write("                                    \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table border=0 cellpadding=0 cellspacing=0 width=100%>\r\n");
      out.write("                                            <tr> \r\n");
      out.write("                                                <td width=\"20\"><img src=\"images/title_bullet1.gif\"></td>\r\n");
      out.write("                                                <td width=\"130\" class=\"sub_tit\">테스트케이스관리</td>\r\n");
      out.write("                                                <td valign=\"bottom\" class=\"point_text\" id=\"flowMsg\" >테스트실행버튼을 클릭하여 테스트를 실행하십시오.</td>\r\n");
      out.write("                                                <td height=\"2\" align=\"right\">\r\n");
      out.write("                                                \t<a id=\"btnNew\" href=\"#\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Image56','','images/btn_newtc_02.jpg',1)\" onclick=\"getTcmngIoMap();\">\r\n");
      out.write("                                                \t\t<img src=\"images/btn_newtc_01.jpg\" name=\"Image56\" width=\"65\" height=\"19\" hspace=\"2\" border=\"0\">\r\n");
      out.write("                                                \t</a>\r\n");
      out.write("                                                \t<a id=\"btnLoad\" href=\"#\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Image57','','images/btn_import_02.jpg',1)\" onclick=\"getTcmngInfo();\">\r\n");
      out.write("                                                \t\t<img src=\"images/btn_import_01.jpg\" name=\"Image57\" width=\"65\" height=\"19\" hspace=\"2\" border=\"0\">\r\n");
      out.write("                                                \t</a>\r\n");
      out.write("                                                \t<!-- \r\n");
      out.write("                                                \t<a id=\"btnSave\" href=\"#\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Image58','','images/btn_savetc_02.jpg',1)\"  onclick=\"doTcSave();\"><img src=\"images/btn_savetc_01.jpg\" name=\"Image58\" width=\"48\" height=\"19\" hspace=\"2\" border=\"0\"></a>\r\n");
      out.write("                                                \t<a id=\"btnReset\" href=\"#\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('Image59','','images/btn_initialize_02.jpg',1)\" onclick=\"reload();\"><img src=\"images/btn_initialize_01.jpg\" name=\"Image59\" width=\"57\" height=\"19\" hspace=\"2\" border=\"0\"></a>\r\n");
      out.write("                                                \t -->\r\n");
      out.write("                                                \t<a id=\"Image58\" href=\"#\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"\"  onclick=\"\">\r\n");
      out.write("                                                \t\t<img src=\"images/btn_savetc_03.jpg\" id=\"Image58 img\" name=\"Image58\" width=\"48\" height=\"19\" hspace=\"2\" border=\"0\">\r\n");
      out.write("                                                \t</a>\r\n");
      out.write("                                                \t<a id=\"Image59\" href=\"#\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"\" onclick=\"\">\r\n");
      out.write("                                                \t\t<img src=\"images/btn_initialize_03.jpg\" id=\"Image59 img\" name=\"Image59\" width=\"57\" height=\"19\" hspace=\"2\" border=\"0\">\r\n");
      out.write("                                                \t</a>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                          </tr>\r\n");
      out.write("                                            <tr > \r\n");
      out.write("                                                <td background=\"images/tit_line_bg.gif\" height=\"6\" colspan=\"4\"><img src=\"images/tit_line_bg.gif\"></td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr > \r\n");
      out.write("                                                <td height=\"10\" colspan=\"4\"></td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                      </table>\r\n");
      out.write("                                    \r\n");
      out.write("                                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                              <td class=\"sub_tit02\"> 테스트케이스 정보</td>\r\n");
      out.write("                        \t\t\t\t  </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td height=\"1\" colspan=\"2\"></td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                      </table>\r\n");
      out.write("                                    \r\n");
      out.write("                                      <table width=\"100%\" border=\"0\" cellpadding=\"1\" cellspacing=\"1\" bgcolor=\"#baccdc\">\r\n");
      out.write("                                          <tr>\r\n");
      out.write("                                            <td width=\"140px\" class=\"tm_left\"> 테스트케이스ID</td>\r\n");
      out.write("                                            <td width=\"35%\" class=\"tm_text\" id=\"txtTcID\">&nbsp;</td>\r\n");
      out.write("                                            <td width=\"150px\" class=\"tm_left\"> 테스트케이스 명</td>\r\n");
      out.write("                                            <td width=\"35%\" class=\"tm_text\" id=\"txtTcName\">&nbsp;</td>\r\n");
      out.write("                                          </tr>\r\n");
      out.write("                                          <tr>\r\n");
      out.write("                                            <td class=\"tm_left\"> 거래코드</td>\r\n");
      out.write("                                            <td class=\"tm_text\" id=\"txtTranCD\">&nbsp;</td>\r\n");
      out.write("                                            <td class=\"tm_left\" rowspan=\"2\"> 테스트케이스 설명</td>\r\n");
      out.write("                                            <td class=\"tm_text\" rowspan=\"2\" id=\"txtTcDesc\">&nbsp;</td>\r\n");
      out.write("                                          </tr>\r\n");
      out.write("                                          <tr>\r\n");
      out.write("                                            <td class=\"tm_left\"> 거래명</td>\r\n");
      out.write("                                            <td class=\"tm_text\" id=\"txtTranName\">&nbsp;</td>\r\n");
      out.write("                                          </tr>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                      <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                          <td height=\"10\" colspan=\"2\"></td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                          <td class=\"sub_tit02\">기본 테스트데이터</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                      </table>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <!-- 그리드 영역 시작  -->\r\n");
      out.write("                                    <table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"2\" cellspacing=\"1\" bgcolor=\"#baccdc\">\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td height=\"100%\" valign=\"top\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t                                        <div id=\"basicsListDiv\">\r\n");
      out.write("\t                                        \t<table id=\"basicsList\"></table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                    <!-- 그리드 영역 종료  -->\r\n");
      out.write("                                    \r\n");
      out.write("                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td height=\"10\" colspan=\"2\"></td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td width=\"200\" class=\"sub_tit02\">테스트케이스 구성</td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                        <div id=\"btnArea2\"  disabled=\"disabled\">\r\n");
      out.write("                                        <table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                          <tr>\r\n");
      out.write("                                            <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                            <td background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick=\"doRowDel();\" style=\"cursor:pointer;\">삭 제</td>\r\n");
      out.write("                                            <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                          </tr>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                          <table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                          <tr>\r\n");
      out.write("                                            <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                            <td background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick=\"doRowCopy();\" style=\"cursor:pointer;\" >복 사</td>\r\n");
      out.write("                                            <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                          </tr>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                          <table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                              <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                              <td background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick=\"setDataAutoCreate();\" style=\"cursor:pointer;\">데이터자동생성</td>\r\n");
      out.write("                                              <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                          </table>\r\n");
      out.write("                                          <table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                              <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                              <td background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick=\"getTcmngAdd();\" style=\"cursor:pointer;\">기존 테스트케이스 추가</td>\r\n");
      out.write("                                              <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                          </table>\r\n");
      out.write("                                          <table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                              <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                              <td background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick=\"addTestData();\" style=\"cursor:pointer;\">기본 테스트데이터 추가</td>\r\n");
      out.write("                                              <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                          </table>\r\n");
      out.write("                                          <table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                              <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                              <td background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick=\"doRowDown();\" style=\"cursor:pointer;\" >▼</td>\r\n");
      out.write("                                              <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                          </table>\r\n");
      out.write("                                          <table border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                              <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                              <td background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick=\"doRowUp();\" style=\"cursor:pointer;\" >▲</td>\r\n");
      out.write("                                              <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                          </table>\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          </td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <!-- 그리드 영역 시작  -->\r\n");
      out.write("                                     <table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"2\" cellspacing=\"1\" bgcolor=\"#baccdc\">\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td height=\"100%\" valign=\"top\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t                                        <div id=\"listDiv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table id=\"list\"></table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                    <!-- 그리드 영역 시작  -->\r\n");
      out.write("                                    \r\n");
      out.write("                                    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\" id=\"btnArea3\" disabled=\"disabled\">\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                        <td height=\"5\" colspan=\"4\"></td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                      <tr>\r\n");
      out.write("                                       <td width=\"100\" height=\"10\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                              <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                              <td id=\"btnExecute\" background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick=\"btnExecute();\" style=\"cursor:pointer;\" >\r\n");
      out.write("                                                <font style=\"cursor:pointer;\">테스트 실행</font>\r\n");
      out.write("                                              </td>\r\n");
      out.write("                                              <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </table></td>\r\n");
      out.write("                                        <td width=\"130\" height=\"10\"><table class=\"btnResult\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"display: none;\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                              <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                              <td id=\"btnResult\" background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick=\"btnResult();\" style=\"cursor:pointer;\" >\r\n");
      out.write("                                                <font style=\"cursor:pointer;\">결과보고서 보기</font>\r\n");
      out.write("                                              </td>\r\n");
      out.write("                                              <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </table></td>\r\n");
      out.write("                                        <td width=\"300\" height=\"10\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                              <td id=\"btnExecute\">\r\n");
      out.write("                                                <span id=\"prcssMsg\" style=\"color: red; font-size: 15px\"></span>\r\n");
      out.write("                                              </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </table></td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                          <table align=\"right\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                              <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                              <td background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick=\"importExcel();\" style=\"cursor:pointer;\" >엑셀업로드</td>\r\n");
      out.write("                                              <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                          </table>\r\n");
      out.write("                                          <table align=\"right\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t                                          <tr>\r\n");
      out.write("\t                                            <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("\t                                            <td background=\"images/btn_img_02.gif\" class=\"btn_text\" onclick=\"exportExcel();\" style=\"cursor:pointer;\" >엑셀다운로드</td>\r\n");
      out.write("\t                                            <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("\t                                          </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("                                      </tr>\r\n");
      out.write("                                    </table></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</form>    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
