package org.apache.jsp.WEB_002dINF.view.msg.popMyQalty;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class popMyQalty_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>전문 테스트로(TESTRO)</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"jqgrid/css/ui-lightness/jquery-ui-1.7.3.custom.css\" media=\"screen\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"jqgrid/js/src/css/ui.jqgrid.css\" media=\"screen\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/TESTRO.ico\" type=\"image/ico\" />\r\n");
      out.write("<style>\r\n");
      out.write("html, body {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    font-size: 75%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jqgrid/js/jquery-1.5.2.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cmn/jquery.blockUI.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jqgrid/js/src/i18n/grid.locale-en.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jqgrid/js/jquery.jqGrid.src.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cmn/popupcalendar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("//창 띄울때 레벨에 따라서 보이고 안보이고, 수정이냐 신규에 따라 화면 변경\r\n");
      out.write("function insertYN()\r\n");
      out.write("{\r\n");
      out.write("\t//기본 값들\r\n");
      out.write("\tvar projectNo = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projNo}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tvar projectName = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projName}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tvar projectStep = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${TestStgeName}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tvar startDate = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startDate}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tvar endDate = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${endDate}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tvar newSave = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${newSave}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t//달력 필드 입력 불가\r\n");
      out.write("\t$(\"#startDate\").attr(\"readonly\",true);\r\n");
      out.write("\t$(\"#endDate\").attr(\"readonly\",true);\r\n");
      out.write("\t//수정일 경우\r\n");
      out.write("\tif(newSave == \"N\"){\t\t\t\t\r\n");
      out.write("\t\t$(\"#projectNo\").val(projectNo);\r\n");
      out.write("\t\t$(\"#projectName\").val(projectName);\r\n");
      out.write("\t\t$(\"#projectStep\").val(projectStep);\r\n");
      out.write("\t\t$(\"#startDate\").val(startDate);\r\n");
      out.write("\t\t$(\"#endDate\").val(endDate);\r\n");
      out.write("\t\t$(\"#projectNo\").attr(\"disabled\",true);\r\n");
      out.write("\t\t$(\"#projectStep\").attr(\"disabled\",true);\r\n");
      out.write("\t\t$(\"#Check\").hide();\r\n");
      out.write("\t\t$(\"#titleName\").text('나의 프로젝트 수정');\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("// iframe resize\r\n");
      out.write("function autoResize(i)\r\n");
      out.write("{\r\n");
      out.write("    var iframeHeight=\r\n");
      out.write("    (i).contentWindow.document.body.scrollHeight;\r\n");
      out.write("    (i).height=iframeHeight+20;\r\n");
      out.write("}\r\n");
      out.write("// 프로젝트 번호, 단계 체크 \r\n");
      out.write("function projectStepCheck(){\r\n");
      out.write("\tvar projectNo = $(\"#projectNo\").val();\r\n");
      out.write("\tvar projectStep = $(\"#projectStep\").val();\r\n");
      out.write("\tif(projectNo  == \"\"){\r\n");
      out.write("\t\talert(\"프로젝트 번호를 입력해 주세요.\");\r\n");
      out.write("\t\tfrm.projectNo.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(projectStep  == \"\"){\r\n");
      out.write("\t\talert(\"테스트단계를 입력해 주세요.\");\r\n");
      out.write("\t\tfrm.projectStep.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.blockUI(); //block시작\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        type:\"POST\",\r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\t\t\"projectNo\": projectNo,\r\n");
      out.write("\t\t\t\"projectStep\":projectStep\r\n");
      out.write("\t\t},\r\n");
      out.write("        dataType:\"json\",\r\n");
      out.write("        async : true,\r\n");
      out.write("        url:\"msg.projectStepCheckMngUser.popMyQalty.do\",\r\n");
      out.write("        success:function(data, status) {\r\n");
      out.write("        \tif (data.errCd){\r\n");
      out.write("\t        \talert('에러코드 : ' + data.errCd + \"\\n에러메시지 : \" + data.errMsg);\r\n");
      out.write("\t        \t$.unblockUI(); //block시작\r\n");
      out.write("        \t}else{\r\n");
      out.write("\t            if(data.check == \"1\"){\t\t\t\t\t\t\t\t\t\t\t\t//같은 프로젝트 번호에 동일한 테스트 단계가 있을경우\r\n");
      out.write("\t            \talert(projectNo+\"의 프로젝트에 동일한 테스트 단계가 있습니다.\");\r\n");
      out.write("\t            \t$.unblockUI(); //block시작\r\n");
      out.write("\t            \treturn false;\r\n");
      out.write("\t            }else{\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//사용가능할 경우\r\n");
      out.write("\t            \talert(\"사용 가능한 테스트 단계입니다.\");\r\n");
      out.write("\t            \t$.unblockUI(); //block시작\r\n");
      out.write("\t            \treturn false;\r\n");
      out.write("\t            }\r\n");
      out.write("        \t}\r\n");
      out.write("        },\r\n");
      out.write("        error:function(request, status, error) {\r\n");
      out.write("        \talert(\"테스트 단계 중복확인중에 오류가 발생하였습니다.[\" + error + \"]\"); \r\n");
      out.write("        \t$.unblockUI(); //block시작\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("//프로젝트 저장\r\n");
      out.write("function projSave(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar projectNo = $(\"#projectNo\").val();\r\n");
      out.write("\tvar projectName = $(\"#projectName\").val();\r\n");
      out.write("\tvar projectStep = $(\"#projectStep\").val();\r\n");
      out.write("\tvar startDate = $(\"#startDate\").val();\r\n");
      out.write("\tvar endDate = $(\"#endDate\").val();\r\n");
      out.write("\tvar newInsert = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${newSave}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\t\t\t\t\t//구분자\r\n");
      out.write("\tvar usrid = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userinfo.usrid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';    //사용자id\r\n");
      out.write("\tif(projectNo  == \"\"){\r\n");
      out.write("\t\talert(\"프로젝트 번호를 입력해 주세요.\");\r\n");
      out.write("\t\tfrm.projectNo.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(projectName  == \"\"){\r\n");
      out.write("\t\talert(\"프로젝트명을 입력해 주세요.\");\r\n");
      out.write("\t\tfrm.projectName.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(projectStep  == \"\"){\r\n");
      out.write("\t\talert(\"테스트단계명을 입력해 주세요.\");\r\n");
      out.write("\t\tfrm.projectStep.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(startDate == \"\"){\r\n");
      out.write("\t\talert(\"시작일을 설정해주세요.\");\r\n");
      out.write("\t\tfrm.startDate.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(endDate == \"\"){\r\n");
      out.write("\t\talert(\"종료일을 설정해주세요.\");\r\n");
      out.write("\t\tfrm.endDate.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(startDate > endDate){\r\n");
      out.write("\t\talert(\"시작일이 종료일보다 큽니다.\");\r\n");
      out.write("\t\tfrm.endDate.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.blockUI(); //block시작\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        type:\"POST\",\r\n");
      out.write("\t\tdata:{\"usrId\": usrid,\r\n");
      out.write("\t\t\t\"projNo\":projectNo,\r\n");
      out.write("\t\t\t\"projName\":projectName,\r\n");
      out.write("\t\t\t\"TestStgeName\":projectStep,\r\n");
      out.write("\t\t\t\"startDate\":startDate,\r\n");
      out.write("\t\t\t\"endDate\":endDate,\r\n");
      out.write("\t\t\t\"newInsert\":newInsert\r\n");
      out.write("\t\t\t},\r\n");
      out.write("        dataType:\"json\",\r\n");
      out.write("        async : true,\r\n");
      out.write("        url:\"msg.saveMyQalty.popMyQalty.do\",\r\n");
      out.write("        success:function(data, status) {\r\n");
      out.write("        \tif (data.errCd){\r\n");
      out.write("\t        \talert('에러코드 : ' + data.errCd + \"\\n에러메시지 : \" + data.errMsg);\r\n");
      out.write("\t        \t$.unblockUI(); //block시작\r\n");
      out.write("        \t}else{\r\n");
      out.write("\t            if(data.userIdSave == \"1\"){\t\t\t\t\t\t\t\t\t\t\t//중복일 경우\r\n");
      out.write("\t            \talert(projectNo+\"의 프로젝트에 동일한 테스트 단계가 있습니다.\");\r\n");
      out.write("\t            \t$.unblockUI(); //block시작\r\n");
      out.write("\t           \t\treturn false;\r\n");
      out.write("\t            }else  if(data.userIdSave == \"2\"){\t\t\t\t\t\t\t\t\t//수정했을 경우\r\n");
      out.write("\t            \talert(\"프로젝트 정보가 수정되었습니다.\");\r\n");
      out.write("\t            \t$.unblockUI(); //block시작\r\n");
      out.write("\t            \twindow.returnValue = 1;\r\n");
      out.write("\t            \tdoClose();\r\n");
      out.write("\t            }else{\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//저장 했을 경우\r\n");
      out.write("\t            \talert(\"프로젝트 정보가 저장되었습니다.\");\r\n");
      out.write("\t            \t$.unblockUI(); //block시작\r\n");
      out.write("\t            \twindow.returnValue = 1;\r\n");
      out.write("\t            \tdoClose();\r\n");
      out.write("\t            }\r\n");
      out.write("        \t}\r\n");
      out.write("        },\r\n");
      out.write("        error:function(request, status, error) {\r\n");
      out.write("        \talert(\"테스트 단계 중복확인중에 오류가 발생하였습니다.[\" + error + \"]\"); \r\n");
      out.write("        \t$.unblockUI(); //block시작\r\n");
      out.write("        \treturn false;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("//창 닫기\r\n");
      out.write("function doClose(){\r\n");
      out.write("\twindow.close();\t\r\n");
      out.write("}\r\n");
      out.write("//값 초기화\r\n");
      out.write("function doClear(){ \r\n");
      out.write("\t$(\"#startDate\").val(\"\");\r\n");
      out.write("\t$(\"#endDate\").val(\"\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body leftmargin=\"0\" topmargin=\"0\" onLoad=\"insertYN()\">\r\n");
      out.write("<form name=\"frm\" method=\"post\">\r\n");
      out.write("\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t    <td width=\"43\"><img src=\"images/pop_tit_01.gif\" width=\"43\" height=\"51\"></td>\r\n");
      out.write("\t    <td background=\"images/pop_tit_02.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t        <td id=\"titleName\" class=\"pop_tit\">나의 프로젝트 등록</td>\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t    </table></td>\r\n");
      out.write("\t    <td width=\"216\"><img src=\"images/pop_tit_03.gif\" width=\"216\" height=\"51\"></td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"3\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td valign=\"top\"><table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"5\" cellspacing=\"1\" bgcolor=\"#baccdc\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td bgcolor=\"#e1e9f0\"><table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"5\" cellspacing=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td valign=\"top\" bgcolor=\"#FFFFFF\"><table width=\"100%\" border=\"0\" cellpadding=\"5\" cellspacing=\"1\"  bgcolor=\"#baccdc\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td bgcolor=\"#e1e9f0\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"5\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td bgcolor=\"#FFFFFF\"><table width=\"100%\" border=\"0\" cellpadding=\"2\" cellspacing=\"0\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td width=\"95\" class=\"box_txt_red\">프로젝트 번호 :</td>\r\n");
      out.write("                            <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                  <td width=\"120\"><input name=\"projectNo\" id=\"projectNo\" type=\"text\" class=\"input_topinq\" style=\"width:230px;ime-mode:disabled;\" maxlength=\"20\" onpaste=\"javascript:return false;\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                              </table></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td class=\"box_txt_red\">프로젝트 명 :</td>\r\n");
      out.write("                            <td><input name=\"projectName\" id=\"projectName\" type=\"text\" class=\"input_topinq\" style=\"width:230px\" maxlength=\"60\"></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td class=\"box_txt_red\">테스트 단계 :</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                            \t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                \t<td width=\"120\"><input name=\"projectStep\" id=\"projectStep\" type=\"text\" class=\"input_topinq\" style=\"width:230px\" maxlength=\"20\"></td>\r\n");
      out.write("                                \t<td>\r\n");
      out.write("                              <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                                <tr id=\"Check\">\r\n");
      out.write("                                  <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                                  <td background=\"images/btn_img_02.gif\" class=\"btn_text\" style=\"cursor:pointer\" onclick=\"projectStepCheck(); return false;\">중복확인</td>\r\n");
      out.write("                                  <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                              </table>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            \t</tr>\r\n");
      out.write("                              </table>\r\n");
      out.write("                             </td>\r\n");
      out.write("                             \r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td class=\"box_txt_red\">테스트 기간 :</td>\r\n");
      out.write("                            <td><input id=\"startDate\" name=\"startDate\" type=\"text\" class=\"input_topinq\" style=\"width:65px\">\r\n");
      out.write("                              <img src=\"images/un_sub_cen_cal.gif\" alt=\"달력\" width=\"23\" height=\"21\" hspace=\"4\" align=\"absmiddle\" style=\"cursor:pointer\" onclick=\"popUpCalendar(this, 'startDate', 'yyyy-mm-dd','CENTER','MIDDLE');\"> ~\r\n");
      out.write("                              <input id=\"endDate\" name=\"endDate\" type=\"text\" class=\"input_topinq\" style=\"width:65px\">\r\n");
      out.write("                              <img src=\"images/un_sub_cen_cal.gif\" alt=\"달력\" width=\"23\" height=\"21\" hspace=\"4\" align=\"absmiddle\" style=\"cursor:pointer\" onclick=\"popUpCalendar(this, 'endDate', 'yyyy-mm-dd','CENTER','MIDDLE');\">\r\n");
      out.write("                              <img src=\"images/btn_eraser.gif\" alt=\"삭제\" width=\"23\" height=\"21\" hspace=\"4\" align=\"absmiddle\" style=\"cursor:pointer\" onclick=\"doClear();\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                          </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("              <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td height=\"5\" colspan=\"3\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td><table border=\"0\" align=\"left\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                        <td background=\"images/btn_img_02.gif\" class=\"btn_text\" style=\"cursor:pointer\" onclick=\"projSave(); return false;\">저 장</td>\r\n");
      out.write("                        <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  <td ><table align=\"right\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td width=\"16\" height=\"21\" background=\"images/btn_img_01.gif\">&nbsp;</td>\r\n");
      out.write("                          <td background=\"images/btn_img_02.gif\" class=\"btn_text\" style=\"cursor:pointer\" onclick=\"doClose(); return false;\">닫 기</td>\r\n");
      out.write("                          <td width=\"10\" background=\"images/btn_img_03.gif\">&nbsp;</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                      </table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("<!-- Start of wrap -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
